version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/ai-chat-app
      GEMINI_API_KEY: AIzaSyC4_7FwlzIevm-4VpSqUkXwgEEg1VfZ52Q
      SECRET_KEY: air-secure-random-key
    depends_on:
      - db